# Generated by Django 4.2.11 on 2024-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_inventoryitem_minimum_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
