# Generated by Django 4.2.11 on 2024-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='oracle_order_date',
            field=models.DateField(),
        ),
    ]
