# Generated by Django 4.2.11 on 2024-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_alter_orderitem_oracle_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_lead_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='request_date',
            field=models.DateField(),
        ),
    ]
