# Generated by Django 4.2.11 on 2024-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_alter_orderitem_order_lead_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='oracle_order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='order_lead_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='request_date',
            field=models.DateField(),
        ),
    ]
