# Generated by Django 4.2.11 on 2024-04-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0012_alter_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='oracle_order_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='oracle_ordered_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='oracle_po',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='order_lead_time',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='requested_by',
        ),
    ]
