# Generated by Django 4.2.11 on 2024-04-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0013_remove_inventoryitem_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('on_order', models.IntegerField(default=0)),
                ('quantity_per_unit', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('minimum_unit', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_date', models.DateField()),
                ('requested_by', models.CharField(max_length=255)),
                ('oracle_order_date', models.DateField()),
                ('oracle_po', models.CharField(max_length=255)),
                ('order_lead_time', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history_items', to='inventory_app.inventoryitem')),
            ],
        ),
    ]
