# Generated by Django 4.2.11 on 2024-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0014_orderitemhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='stores', max_length=255),
        ),
        migrations.AddField(
            model_name='itemwithdrawal',
            name='location',
            field=models.CharField(default='stores', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='location',
            field=models.CharField(default='stores', max_length=255),
        ),
    ]
