# Generated by Django 4.2.11 on 2024-04-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0015_inventoryitem_location_itemwithdrawal_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(default='Stores', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory_app.location'),
        ),
    ]
