# Generated by Django 4.2.11 on 2024-04-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0016_location_alter_inventoryitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory_app.location'),
        ),
        migrations.AlterField(
            model_name='itemwithdrawal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='Stores', max_length=255),
        ),
    ]
