# Generated by Django 5.1 on 2024-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0020_alter_itemwithdrawal_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_id',
            field=models.CharField(default='No barcode', max_length=255),
        ),
    ]
