# Generated by Django 4.2.11 on 2024-03-31 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_inventoryitem_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_withdrawn', models.DateTimeField(default=django.utils.timezone.now)),
                ('units_withdrawn', models.IntegerField()),
                ('withdrawn_by', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.inventoryitem')),
            ],
        ),
    ]
