# Generated by Django 4.2.11 on 2024-04-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0017_alter_inventoryitem_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemwithdrawal',
            name='location',
        ),
        migrations.AddField(
            model_name='itemwithdrawal',
            name='location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='inventory_app.location'),
        ),
    ]
