# Generated by Django 4.2.11 on 2024-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0018_remove_itemwithdrawal_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemwithdrawal',
            name='location_fk',
        ),
        migrations.AddField(
            model_name='itemwithdrawal',
            name='location',
            field=models.CharField(default='stores', max_length=255),
        ),
    ]
