# Generated by Django 4.2.11 on 2024-04-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0019_remove_itemwithdrawal_location_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwithdrawal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='inventory_app.location'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_locations', to='inventory_app.location'),
        ),
        migrations.DeleteModel(
            name='OrderItemHistory',
        ),
    ]
