name: Use PR to tracker workflow

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  call-pr-to-tracker:
    uses: DigitalShoestringSolutions/CommonWorkflows/.github/workflows/add_prs_to_tracker.yml@master
    secrets:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
